# This is a general Jupyter notebook for Computer Graphics modules in Visual Code
## Introduction
this is a jupyter notebook fully authored in inside visual Code!
<b>and it works well!
- this is bullet one!
> this is quote
>> this is double quote

In [ ]:
# Hello Jupyter as python comment!
# this is another text!
import numpy as np
msg = 'hello GL \n Jupyter world!'
print(msg)

In [1]:
import sys
sys.path

['/Users/Giwrgakis/MyProjects/glGA-SDK/notebooks/pyCG/RealTimeRendering/introToPyCG',
 '/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.5.702919634/pythonFiles',
 '/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.5.702919634/pythonFiles',
 '/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.5.702919634/pythonFiles/lib/python',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python37.zip',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/lib-dynload',
 '',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages/aeosa',
 '/Users/Giwrgakis/MyProjects/glGA-SDK/packages',
 '/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages/IPython/extensions',
 '/Users/Giwrgakis/.ipython']

## Test python system path below:

In [1]:
import sys
for p in sys.path:
	print(p)

/Users/Giwrgakis/MyProjects/glGA-SDK/notebooks/pyCG/RealTimeRendering/introToPyCG
/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/vscode_datascience_helpers/../.does-not-exist
/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles
/Users/Giwrgakis/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/lib/python
/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python37.zip
/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7
/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/lib-dynload

/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages
/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages/aeosa
/Users/Giwrgakis/MyProjects/glGA-SDK/packages
/Users/Giwrgakis/opt/anaconda3/envs/glGA37/lib/python3.7/site-packages/IPython/extensions
/Users/Giwrgakis/.ipython


In [3]:
def f():
    print("hello from f()")

def y(f):
    f
    print("hello from y()")

y(f())

hello from f()


## pyAssimp package test
@@@

In [ ]:
import os
import sys
print (os.name)
#print (sys.path)

from pyassimp import * #the pip pyassimp module
#from assimp import * # the conda assimp module
#import assimp
#import pyassimp
scene = load('./box.fbx')
assert len(scene.meshes)
mesh = scene.meshes[0]

assert len(mesh.vertices)
print(mesh.vertices[0])
for c in scene.rootnode.children:
    print(str(c))

# don't forget this one, or you will leak!
release(scene)

## pyIMGUI package test
@@@


In [ ]:
"""
# example pyIMGUI access
# API seems like working, maybe not inside Jupyter or wrong render loop
import imgui

#init context
imgui.create_context()
imgui.get_io().display_size = 100,100
# imgui.show_demo_window()
imgui.get_io().fonts.get_tex_data_as_rgba32()

#imgui.text("Hello, world %d", 123)

# start new frame context
imgui.new_frame()

# open new window context
imgui.begin("Your first window!", True)

# draw text label inside of current window
imgui.text("Hello world!")

# close current window context
imgui.end()

# pass all drawing comands to the rendering pipeline
# and close frame context
i=1
while i>0:
    imgui.render()
    imgui.end_frame()
"""

## another pyimgui and pySDL2 example

In [ ]:
%run ../pyglGA/basicWindow.py


## pySDL2 package test
directly from the github examples

In [ ]:
# sample pySDL2 access
import sys
import ctypes

from OpenGL import GL, GLU
import sdl2

def run():
    if sdl2.SDL_Init(sdl2.SDL_INIT_VIDEO) != 0:
        print(sdl2.SDL_GetError())
        return -1

    window = sdl2.SDL_CreateWindow(b"OpenGL demo",
                                   sdl2.SDL_WINDOWPOS_UNDEFINED,
                                   sdl2.SDL_WINDOWPOS_UNDEFINED, 800, 600,
                                   sdl2.SDL_WINDOW_OPENGL)
    if not window:
        print(sdl2.SDL_GetError())
        return -1

    context = sdl2.SDL_GL_CreateContext(window)

    GL.glMatrixMode(GL.GL_PROJECTION | GL.GL_MODELVIEW)
    GL.glLoadIdentity()
    GL.glOrtho(-400, 400, 300, -300, 0, 1)

    x = 0.0
    y = 30.0

    event = sdl2.SDL_Event()
    running = True
    while running:
        while sdl2.SDL_PollEvent(ctypes.byref(event)) != 0:
            if event.type == sdl2.SDL_QUIT:
                running = False

        GL.glClearColor(0, 0, 0, 1)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)
        GL.glRotatef(10.0, 0.0, 0.0, 1.0)
        GL.glBegin(GL.GL_TRIANGLES)
        GL.glColor3f(1.0, 0.0, 0.0)
        GL.glVertex2f(x, y + 90.0)
        GL.glColor3f(0.0, 1.0, 0.0)
        GL.glVertex2f(x + 90.0, y - 90.0)
        GL.glColor3f(0.0, 0.0, 1.0)
        GL.glVertex2f(x - 90.0, y - 90.0)
        GL.glEnd()

        sdl2.SDL_GL_SwapWindow(window)
        sdl2.SDL_Delay(10)
    sdl2.SDL_GL_DeleteContext(context)
    sdl2.SDL_DestroyWindow(window)
    sdl2.SDL_Quit()
    return 0

run()


## igl package test
@@@

In [ ]:
# sample igl access
import sys, os

# Add the igl library to the modules search path
sys.path.insert(0, os.getcwd() + "/../")
#import pyigl as igl
import igl

#from shared import TUTORIAL_SHARED_PATH, check_dependencies

#dependencies = ["glfw"]
#check_dependencies(dependencies)

# Load a mesh in OFF format
V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
igl.readOFF(TUTORIAL_SHARED_PATH + "Cube.off", V, F)

# Plot the mesh
viewer = igl.glfw.Viewer()
viewer.data().set_mesh(V, F)
viewer.launch()

In [ ]:
# another sample from tutorial
import igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact

import os
# root_folder = os.getcwd()
root_folder = os.path.join(os.getcwd(), "tutorial")
V = np.array([
    [0., 0, 0],
    [1, 0, 0],
    [1, 1, 1],
    [2, 1, 0]
])

F = np.array([
    [0, 1, 2],
    [1, 3, 2]
])

plot(V, F)

## Clifford GA test
@@@

In [ ]:
# sample clifford access
from clifford.g3 import *  # import GA for 3D space
from math import e, pi
a = e1 + 2*e2 + 3*e3 # vector 
R = e**(pi/4*e12)    # rotor 
R*a*~R    # rotate the vector  

## galgebra test

In [ ]:
from sympy import symbols
from galgebra.ga import Ga

from galgebra.printer import Format
Format(Fmode = False, Dmode = True)

st4coords = (t,x,y,z) = symbols('t x y z', real=True)
st4 = Ga('e',
         g=[1,-1,-1,-1],
         coords=st4coords)

M = st4.mv('M','mv',f = True)

M.grade(3).Fmt(3,r'\langle \mathbf{M} \rangle _3')

## pyGLM package test
https://github.com/Zuzu-Typ/PyGLM/blob/master/wiki/function-reference/README.md 

In [4]:
# sample GLM access
import glm
import math
v = glm.vec4(1,2,0,1)
v.x = 2
print(v.xyzw)
print("v:",v)
norm_v = glm.normalize(v)
#len_v = math.sqrt(v.to_list*v.to_list)
#print("len_v:", norm_v)
print("norm_v:", norm_v)
transMat = glm.mat4(1.0)
rotMat = glm.mat4(1.0)
mat1 = glm.mat4(1., 0., 0., 0.,
                    0., 1., 0., 0.,
                    0., 0., 1., 0.,
                    -10., 10., 10., 1.)
axis = glm.vec3(1.0,1.0,1.0)
angle = 90
rotMat = glm.rotate(glm.mat4(), glm.radians(angle), axis)
eye = glm.vec3(1.0, 1.0, 1.0)
target = glm.vec3(10,10,10)
up = glm.vec3(0.0, 1.0, 0.0)
matLookAt = glm.lookAtLH(glm.normalize(eye), glm.normalize(target), glm.normalize(up))
print("\n------ Matrices test ------- \n")
print("\nmat1 mat4:")
print(mat1)
print("\nrotMat mat4:")
print(glm.transpose(rotMat))
print("\nmatLookAt:")
print(matLookAt)
print("\nmatLookAt transpose:")
print(glm.transpose(matLookAt))
print("\n------ Quaternions test ------- \n")
# remember GLM is scalar first on quats i.e. q = w, x, y, z
#q = glm.quat_cast(mat1)
q = glm.quat(1.0,1.0,1.0,1.0)
q2 = glm.quat(4.0,1.0,2.0,3.0)
q3 = glm.slerp(glm.normalize(q),glm.normalize(q2),0.5)

print("\nq3 slerp: ",glm.normalize(q3), "with w: ", q3.w)
qq2 = glm.normalize(q*q2)
print("\nqq2: ",qq2)
print("qq2.w: ",qq2.w)
transMat = glm.translate(glm.mat4(1.0), glm.vec3(10.,20.,30.))
print("\ntransmat mat4:")
print(transMat)
print("\ntransmat mat4 transpose:")
print(glm.transpose(transMat))
#glm.ortho(left: float, right: float, bottom: float, top: float, zNear: float, zFar: float)
orthoMat = glm.ortho(-100.0, 100.0, -100.0, 100.0, 1.0, 100.0)
print("\northoMat:")
print(orthoMat)
print("\northoMat trans:")
print(glm.transpose(orthoMat))
# lm.perspective(fovy: float, aspect: float, near: float, far: float) -> fmat4x4
#glm.perspectiveFov(fov: float, width: float, height: float, near: float, far: float) -> fmat4x4

#perspMat = glm.perspectiveFov(90.0, 512, 512, 0.1, 100)
perspMat = glm.perspective(glm.radians(45.0), 1.33, 0.1, 100)
print("\nperspMat:")
print(perspMat)
print("\nperspMat trans:")
print(glm.transpose(perspMat))
perspMat2 = glm.perspective(glm.radians(90.0), 1, 0.1, 10)
print("\nperspMat2:")
print(perspMat2)
print("\nperspMat2 trans:")
print(glm.transpose(perspMat2))

#glm.frustum(left: float, right: float, bottom: float, top: float, near: float, far: float) -> fmat4x4
frustumMat = glm.frustum(-10.0, 10.0,-10.0,10.0, 0.1, 100)
print("\nfrustumMat:")
print(frustumMat)
print("\nfrustumMat trans:")
print(glm.transpose(frustumMat))

eye = glm.vec3(0.0, 0.0, -1.0)
target = glm.vec3(0.0, 0.0, 0.0)
up = glm.vec3(0.0, 1.0, 0.0)
lookat = glm.lookAtLH(eye, target, up)
print("\nlookat:")
print(lookat)
print("\nlookat trans:")
print(glm.transpose(lookat))


vec4(            2,            2,            0,            1 )
v: vec4(            2,            2,            0,            1 )
norm_v: vec4(     0.666667,     0.666667,            0,     0.333333 )

------ Matrices test ------- 


mat1 mat4:
[            1 |            0 |            0 |            0 ]
[            0 |            1 |            0 |            0 ]
[            0 |            0 |            1 |            0 ]
[          -10 |           10 |           10 |            1 ]

rotMat mat4:
[     0.333333 |    -0.244017 |     0.910684 |            0 ]
[     0.910684 |     0.333333 |    -0.244017 |            0 ]
[    -0.244017 |     0.910684 |     0.333333 |            0 ]
[            0 |            0 |            0 |            1 ]

matLookAt:
[    -0.707107 |    -0.408248 |     -0.57735 |            0 ]
[            0 |     0.816497 |     -0.57735 |            0 ]
[     0.707107 |    -0.408248 |     -0.57735 |            0 ]
[           -0 |           -0 |            1 |  

In [ ]:
#dir(help(glm))
#help(glm.dquat)
print("\n------ Dual Quaternions tests ------- \n")
src_q1 = glm.quat(1.0,2.0,3.0,4.0) # real part
src_q2 = glm.quat(5.0,6.0,7.0,8.0) # real part
#dual_q = glm.(src_q1,src_q2)
#dual_q= glm.normalize(dual_q)



In [ ]:
#help(glm.rotate)
help(glm.quat)

## numpy test

In [ ]:
import numpy as np
from numpy.linalg import inv
import math

M1 = np.identity(4)
F3 = np.identity(4)
M2 = np.array([
    [1,0,0,1],
    [0,1,0,2],
    [0,0,1,3],
    [0,0,0,1]
])
T = np.array([
                [1],
                [2],
                [3],
                [1]
            ])

Row = np.array(
    [1, 2, 3, 1]
)
Row2 = np.array((1, 2, 3, 1))
Row3 = np.array([1, 2, 3, 1], dtype=np.float,order='F')

cVec = np.identity(4)
#Row = Row.reshape(4,1)
#Row = Row.transpose()
print(f"F3 shape: {F3.shape}")
F3 = M2 @ T
print("F3=M2@T: \n",F3)
print("M1: \n",M1)
print("M2: \n",M2)
print("M2 inverse: \n",inv(M2))
print("T: \n",T)
print(f"M1 @ F3: \n {M1 @ F3}")
print(f"T shape: {T.shape}")
print(f"M2 shape: {M2.shape}")
print(f"M2 * T: \n {M2 @ T}")
print(f"Row shape: {Row.shape}")
print("Row: \n", Row)
print(f"Row2 shape: {Row2.shape}")
print("Row2: \n", Row2)
print(f"Row3 shape: {Row3.shape}")
print("Row3: \n", Row3)
print(f"Row @ T: \n {Row @ T}")
cVec = M2[:3, 3] #2D array slicing: three rows, third column
print(f"cVec: \n {cVec}")
print(f"M2[]: {M2[2,3]}") #[row, column]
print(f"T[]: {T[2,0]}") #[row, column]
#print(f"T @ Row: \n {T @ Row}") # cannot perform this matrix multiplication
print(f"cos[0]: {glm.cos(glm.radians(0))}")
print(f"cos[90]: {glm.cos(glm.radians(90.0))}")
print(f"cos[90]: {round(glm.cos(np.pi/2))}")
print(f"cos[90] math: {math.cos(np.pi/2)}")
print(f"cos[pi/4]: {glm.cos(glm.radians(45.0))}")
print(f"sin[0]: {glm.sin(0)}")
print(f"sin[90]: {glm.sin(glm.radians(90))}")
print("pi in degrees is: ", glm.degrees(np.pi))
x, y, z = np.array([1.0, 2.0, 3.0])
print(f'{x},{y},{z}')

TNorm = T[:4]
print(f"TNorm: {TNorm}")
RowNorm = Row[:4]
print(f"RowNorm: {RowNorm}")

In [7]:
import numpy as np
from numpy.linalg import inv

M2 = np.array([
    [1,0,0,1],
    [0,1,0,2],
    [0,0,1,3],
    [0,0,0,1]
])
M3 = np.array([
    [1,0,0,2],
    [0,1,0,3],
    [0,0,1,4],
    [0,0,0,1]
])
M4 = M3 @ M2
print(M4)
print("M4 inverse: \n",inv(M4))
str = f"""this is a compound string, \nM4:{M4} \n"""
f"""and its inverse: \n {inv(M4)}"""
print(str)

matDict = {}
matDict['M3']=M3
for key, value in matDict.items():
    print(key, value)

[[1 0 0 3]
 [0 1 0 5]
 [0 0 1 7]
 [0 0 0 1]]
M4 inverse: 
 [[ 1.  0.  0. -3.]
 [ 0.  1.  0. -5.]
 [ 0.  0.  1. -7.]
 [ 0.  0.  0.  1.]]
this is a compound string, 
M4:[[1 0 0 3]
 [0 1 0 5]
 [0 0 1 7]
 [0 0 0 1]] 

M3 [[1 0 0 2]
 [0 1 0 3]
 [0 0 1 4]
 [0 0 0 1]]


## Scipy spatial transform rotation tests

In [ ]:
from scipy.spatial.transform import Rotation as R

rot = R.from_quat([1.0, 2.0, 3.0, 4.0])

print("rot as quat", rot.as_quat())
print("rot as euler", rot.as_euler('xyz', degrees=True))
print("rot as vector",rot.as_matrix())
print("rot as rot-vec",rot.as_rotvec())

rot2 = R.from_rotvec(np.pi/2 * np.array([0, 0, 1]))
print("\nrot2 as quat:", rot2.as_quat())
print("rot2 as rotvec:", rot2.as_rotvec())
print("rot2 as euler:",rot2.as_euler('xyz', degrees=True))
print("\nQuaternion multiplication")
p = R.from_quat([1.0, 1.0, 1.0, 1.0])
q = R.from_quat([1.0, 2.0, 3.0, 4.0])
print(p.as_euler('xyz', degrees=True))
print(p.as_quat())
print(q.as_euler('xyz', degrees=True))
print(q.as_quat())

pq = p * q
print("\npq.as_quat():\t", pq.as_quat())
print(pq.as_matrix())

## List, Dict, Tuple test

In [1]:
graph = {"A":["D", "C", "B"],
                "B":["E"],
                "C":["G", "F"],
                "D":["H"],
                "E":["I"],
                "F":["J"]}
graphList = ["A", "B", "C"]
stack = ["E", "F", "G"]
data=[]

In [9]:
#next(iter(graph)) #first element in dictionary
if data:
    print("yes data is NOT empty!")

In [3]:
graphList[-1]

'C'

In [ ]:
#graphList = list()
iter = iter(graphList)
#iter = iter("")

In [ ]:
hasNext = False
value = next(iter, None)
if value != None:
    hasNext = True
    print(f"Has next value: {hasNext} and is: {value}")
else:
    hasNext = False
    print(f"Has NO next value: {hasNext} and is: {value}")

In [ ]:
stack.pop()
print(stack)

In [ ]:
#graphList[0]
graph["Z"]={}
graph["Z"][""]= ("1")
print(graph["Z"])
print(graph)

In [ ]:
source = "F"
if source not in graph:
    print(f"{source} not in graph")
else:
    print(f"{source} is in graph")
    for neighbor in graph[source]:
        print(neighbor)



In [ ]:
#kwargs example
def concatenate(**kwargs):
    result = ""
    # Iterating over the Python kwargs dictionary
    for arg in kwargs.values():
        result += arg
    for key in kwargs:
        print(key, " -> ",kwargs[key])
    return result

print(concatenate(a="Real", b="Python", c="Is", d="Great", e="!"))

In [ ]:
import numpy as np
import math

M1 = np.identity(4)
T = np.array([
                [1],
                [2],
                [3],
                [1]
            ])

def update(**kwargs):
    for key in kwargs:
        print(key, " -> ",kwargs[key])
        if (key == "a"):
            print("found: ", key, "with value: ", kwargs[key])
        if (key == "l2world"):
            print("found: ", key, "with value: ", kwargs[key])

def update2(**kwargs):
    key = "l2world"
    key2 = "trs"
    key3 = "l2cam"
    if key in kwargs:
        print("found: ", key, "with value: ", kwargs[key])
    if key2 in kwargs:
        print("found: ", key2, "with value: ", kwargs[key2])
    if key3 in kwargs:
        print("found: ", key3, "with value: ", kwargs[key3])

#update2(l2world=M1, trs=None)
update2(l2cam=M1, l2world=T)

In [15]:
#generate a unique ID and assign it to a a dictionary
import uuid
import time
import random
import pprint
from typing import List, Dict

x = uuid.uuid1()
x.int

class Entity():
    def __init__(self, id=0):
        self._id = id

class Component():
    def __init__(self):
        self._id = uuid.uuid4().int

node1 = Entity(uuid.uuid1().int)
node2 = Entity(uuid.uuid1().int)
comp1 = Component()
comp2 = Component()
comp3 = Component()
comp4 = Component()

entDict = dict()
compList = list()
compList.append(comp1)
compList.append(comp2)
entDict[node1._id] = compList
entDict[node2._id] = [comp3]

#add one component
cList = entDict[node1._id]
cList.append(comp4)

for key, value in entDict.items():
    #print("\n key: ",key, "with value: ", value)
    for el in value: #search a List value for the Dict
        print(el)
        if el is comp1: #search a specific element of the list
            print(f"\n YES!!!! we finally got {comp1} in dict value list: {value} part of {entDict[key]}")

print("pretty print".center(100, '-'))
pprint.pprint(entDict, width = 10)



 YES!!!! we finally got <__main__.Component object at 0x7fdda052f310> in dict value list: [<__main__.Component object at 0x7fdda052f310>, <__main__.Component object at 0x7fdd9079c950>, <__main__.Component object at 0x7fdda052f810>] part of [<__main__.Component object at 0x7fdda052f310>, <__main__.Component object at 0x7fdd9079c950>, <__main__.Component object at 0x7fdda052f810>]
--------------------------------------------pretty print--------------------------------------------
{53614273283624656701191352661259063586: [<__main__.Component object at 0x7fdda052f310>,
 53614308144016162977499893820597211426: [<__main__.Component object at 0x7fdda052f910>]}


In [22]:
componentsList = list()

componentsList.append(comp1)
componentsList.append(comp2)
componentsList.append(comp3)
componentsList.append(comp1)


for el in componentsList:
    print(el)
    if el is comp1:
        print(f" \n GREAT: found {el} in {componentsList} at {componentsList.index(el)}")
    if el is comp3:
        print(f" \n GREAT: found {el} in {componentsList} at {componentsList.index(el)}")

components = set()

components.add(comp1)
components.add(comp2)
components.add(comp3)
components.add(comp1)

for element in components:
    print(element)

ent1 = Entity()
ent2 = Entity()
entityDict = {ent1: "comp1", ent2:["comp2", "comp3", "comp4"]}

for key in entityDict:
    print(f"\n{key} with value: {entityDict[key]}")

com2 = "comp2"
if "comp2" in entityDict.values():
    print("found comp2")

for key, value in entityDict.items():
    if value == "comp1":
        print("\nfound comp1!\n")
    elif com2 in value:
         print(f"\nfound comp2 in the dict value list: {value} !\n")
    

print("\n\n", entityDict.items())

print("pretty print".center(100, '-'))
pprint.pprint(entDict, width = 10)


 
 GREAT: found <__main__.Component object at 0x7fdda052f310> in [<__main__.Component object at 0x7fdda052f310>, <__main__.Component object at 0x7fdd9079c950>, <__main__.Component object at 0x7fdda052f910>, <__main__.Component object at 0x7fdda052f310>] at 0
 
 GREAT: found <__main__.Component object at 0x7fdda052f910> in [<__main__.Component object at 0x7fdda052f310>, <__main__.Component object at 0x7fdd9079c950>, <__main__.Component object at 0x7fdda052f910>, <__main__.Component object at 0x7fdda052f310>] at 2
 
 GREAT: found <__main__.Component object at 0x7fdda052f310> in [<__main__.Component object at 0x7fdda052f310>, <__main__.Component object at 0x7fdd9079c950>, <__main__.Component object at 0x7fdda052f910>, <__main__.Component object at 0x7fdda052f310>] at 0

<__main__.Entity object at 0x7fddb0c885d0> with value: comp1

<__main__.Entity object at 0x7fdd90759350> with value: ['comp2', 'comp3', 'comp4']

found comp1!


found comp2 in the dict value list: ['comp2', 'comp3', 'comp4

## dictionary population tests

In [2]:
import numpy as np
uniform={}

key = 'modelviewproj'
value = np.identity(4)

uniform[key]=value
print(uniform)

{'modelviewproj': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])}


## Generator, Iterator test

In [69]:
class Node:
    def __init__(self):
        pass
    def __str__(self):
        return f"a Node class object"

node = Node()
scene = ["root", "node2", "node4",  "trans4", node]
iterS = iter(scene)
iterS2 = iter(scene)
iterS3 = iter(scene)

In [70]:
for node in scene:
    print(node)
    if node == "root2":
        print("found it!")
        break
    


root
node2
node4
trans4
a Node class object


In [ ]:
x = scene[-1]
print(x)

In [ ]:
scene

In [ ]:
id(x) == id(node)

In [ ]:
scene.append(iterS)
scene

In [ ]:
localIter = scene[-1]
next(localIter)

In [ ]:
scene

In [ ]:
localIter2 = scene.pop()
scene

In [ ]:
next(localIter2)

In [ ]:
list(iterS3)

In [ ]:
# our own infinite iterator
try:
    print(next(iterS3))
except StopIteration:
    print("end of iteration, reseting iterator")
    scene.pop()
    iterS3 = iter(scene)

In [ ]:
# our simple generator
def sceneGenerator():
    for node in scene:
        yield node

sceneIter = sceneGenerator()

In [ ]:
next(sceneIter)

In [ ]:
node2 = Node()
node3 = Node()
scene.append(node2)
scene.append(node3)
scene

In [ ]:
#slicing list
print("original scene is:", str(scene))
element = "trans4"
indexEl = scene.index(element)
newScene = scene[:indexEl]
print("sliced scene is:", str(newScene))

In [ ]:
#reverse list
reverseNewScene = newScene.reverse()
print("sliced scene is:", reverseNewScene)

In [ ]:
rs = newScene[::-1]
print(rs)

## pyOpenVR package test

In [ ]:
import openvr
dir(help(openvr))

In [ ]:
# sample pyopenVR

import sys
import time
import openvr

openvr.init(openvr.VRApplication_Scene)
poses = []  # will be populated with proper type after first call
for i in range(100):
    poses, _ = openvr.VRCompositor().waitGetPoses(poses, None)
    hmd_pose = poses[openvr.k_unTrackedDeviceIndex_Hmd]
    print(hmd_pose.mDeviceToAbsoluteTracking)
    sys.stdout.flush()
    time.sleep(0.2)
openvr.shutdown()



In [ ]:
# it seems it required win32 to operate
from openvr.gl_renderer import OpenVrGlRenderer
from openvr.color_cube_actor import ColorCubeActor
from openvr.glframework.sdl_app import SdlApp

if __name__ == "__main__":
	renderer = OpenVrGlRenderer(multisample=2)
	renderer.append(ColorCubeActor())
	with SdlApp(renderer, "sdl2 OpenVR color cube") as app:
		app.run_loop()

## pyVulkan test
win32 extensions mainly

In [ ]:
# need so rework for surface_xlib under cocoa, but seems like working otherwise
%run example_vulkan.py

## matplotlob test

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

N = 50
x = np.random.rand(N)
y = np.random.rand(N)

colors = np.random.rand(N)
area = np.pi * (15 * np.random.rand(N)) **2  # 0 to 15 points radiuses

plt.scatter(x ,y, area, colors, alpha=0.5)
plt.show()

## pygame test

In [ ]:
import pygame
from pygame.locals import *
 
class App:
    def __init__(self):
        self._running = True
        self._display_surf = None
        self.size = self.weight, self.height = 640, 400
 
    def on_init(self):
        pygame.init()
        self._display_surf = pygame.display.set_mode(self.size, pygame.HWSURFACE | pygame.DOUBLEBUF)
        self._running = True
 
    def on_event(self, event):
        if event.type == pygame.QUIT:
            self._running = False
    def on_loop(self):
        pass
    def on_render(self):
        pass
    def on_cleanup(self):
        pygame.quit()
 
    def on_execute(self):
        if self.on_init() == False:
            self._running = False
 
        while( self._running ):
            for event in pygame.event.get():
                self.on_event(event)
            self.on_loop()
            self.on_render()
        self.on_cleanup()
 
if __name__ == "__main__" :
    theApp = App()
    theApp.on_execute()

## imageio test

In [ ]:
# on of the best imaging modules to load any image format
# https://imageio.readthedocs.io/en/latest/formats.html
import imageio

im = imageio.imread("imageio:chelsea.png")
#im = imageio.imread("output.ppm")
print(im.shape)

In [ ]:
# Load an HDR image (supported by imageio)
# otherwise use opencv: https://www.learnopencv.com/high-dynamic-range-hdr-imaging-using-opencv-cpp-python/ 
#

#imageio.plugins.freeimage.download()
#im2 = imageio.imread('imageio:uffizi_probe.hdr',format='HDR-FI')
#print(im2.shape)

## read image in Jupyter

In [ ]:
import numpy as np 
import imageio
import matplotlib.pyplot as plt
from PIL import Image
#im1 = imageio.imread("imageio:output.ppm") #Read the image from the desktop
im1 = imageio.imread("imageio:chelsea.png") #Read the image from the desktop
print(im1.shape) #Returns the number of rows, columns and channels 
plt.imshow(im1)
plt.show()

### ray trace sample script

In [ ]:
!python raytrace.py

## glfw test

In [ ]:
import glfw

def main():
    # Initialize the library
    if not glfw.init():
        return
    # Create a windowed mode window and its OpenGL context
    window = glfw.create_window(640, 480, "Hello World", None, None)
    if not window:
        glfw.terminate()
        return

    # Make the window's context current
    glfw.make_context_current(window)

    # Loop until the user closes the window
    while not glfw.window_should_close(window):
        # Render here, e.g. using pyOpenGL

        # Swap front and back buffers
       # glfw.swap_buffers(window)

        # Poll for and process events
        glfw.poll_events()

    glfw.terminate()

if __name__ == "__main__":
    main()

## tesselation shader example

In [ ]:
# this shoudl work on another gfx card with OpenGL 4.6 support
import inspect 
import glfw 
import numpy
from OpenGL.GL import *
from OpenGL.GL import shaders

'''
glfw.init()
tile_size, tile_count = 80, 8
width = tile_size * tile_count
glfw.window_hint(glfw.SAMPLES, 16)
window = glfw.create_window(width, width, 'tessellation demo', None, None)
glfw.make_context_current(window)
'''

if not glfw.init():
    print("cannot init glfw")
# Create a windowed mode window and its OpenGL context
window = glfw.create_window(640, 480, "tessellation World", None, None)
if not window:
    glfw.terminate()
    print("cannot create glfw window")

    # Make the window's context current
    glfw.make_context_current(window)

triangle = numpy.array([
    [-0.9, -0.9, 0.5],  # lower left
    [ 0.9, -0.9, 0.5],  # lower right
    [ 0.0,  0.9, 0.5],  # top
], dtype=numpy.float32)
OpenGL.GL.glBindVertexArray(OpenGL.GL.glGenVertexArrays(1))
#vertex_array_object = glGenVertexArrays()
#glBindVertexArray(vertex_array_object)
'''
vao = GLuint(0)
vao = glGenVertexArrays(1)
glBindVertexArray(vao)
'''
glBindBuffer(GL_ARRAY_BUFFER, glGenBuffers(1))
glBufferData(GL_ARRAY_BUFFER, triangle, GL_STATIC_DRAW)
glEnableVertexAttribArray(0)
glVertexAttribPointer(index=0, size=3, type=GL_FLOAT, normalized=False, stride=0, pointer=None)
program = shaders.compileProgram(
    shaders.compileShader(source=inspect.cleandoc('''
        #version 410 core
        in vec3 aPos;
        void main() {
            gl_Position = vec4(aPos, 1);
        }
    '''), shaderType=GL_VERTEX_SHADER),
    # Tessellation control shader not defined here because default is OK.
    shaders.compileShader(source=inspect.cleandoc('''
        #version 410 core
        layout(triangles) in;
        void main() {
            gl_Position = (gl_TessCoord.x * gl_in[0].gl_Position) +
                          (gl_TessCoord.y * gl_in[1].gl_Position) +
                          (gl_TessCoord.z * gl_in[2].gl_Position);
        }
    '''), shaderType=GL_TESS_EVALUATION_SHADER),
    shaders.compileShader(source=inspect.cleandoc('''
        #version 410 core
        out vec4 fragColor;
        void main() {
            fragColor = vec4(vec3(0.1), 1);  // dark gray
        }
    '''), shaderType=GL_FRAGMENT_SHADER),)
glUseProgram(program)
glPolygonMode(GL_FRONT_AND_BACK, GL_LINE)
glPatchParameteri(GL_PATCH_VERTICES, 3)
glClearColor(0.95, 0.95, 0.95, 1)  # pale gray
outer_levels = numpy.array([1, 1, 1, 1], dtype=numpy.float32)
inner_levels = numpy.array([1, 1], dtype=numpy.float32)
while not glfw.window_should_close(window):
    glClear(GL_COLOR_BUFFER_BIT)
    for outer in range(tile_count + 1):  # increase outer tessellation factors left to right
        for inner in range(tile_count + 1):  # inner tesselation factors top to bottom
            glViewport(outer * tile_size, width - inner * tile_size, tile_size, tile_size)
            outer_levels[:] = [outer + 1] * 4  # range 1 to 9; zero means no triangles at all
            inner_levels[:] = [inner] * 2  # range 0 to 8
            glPatchParameterfv(GL_PATCH_DEFAULT_OUTER_LEVEL, outer_levels)
            glPatchParameterfv(GL_PATCH_DEFAULT_INNER_LEVEL, inner_levels)
            glDrawArrays(GL_PATCHES, 0, 3)
    glfw.swap_buffers(window)
    glfw.poll_events()
glfw.terminate()

## pygame example

In [ ]:
import OpenGL.GL as GL
import OpenGL.GL.shaders
import ctypes
import pygame
import numpy

vertex_shader = """
#version 410
in vec4 position;
void main()
{
   gl_Position = position;
}
"""

fragment_shader = """
#version 410
void main()
{
   gl_FragColor = vec4(1.0f, 1.0f, 1.0f, 1.0f);
}
"""

vertices = [ 0.6,  0.6, 0.0, 1.0,
            -0.6,  0.6, 0.0, 1.0,
             0.0, -0.6, 0.0, 1.0]

vertices = numpy.array(vertices, dtype=numpy.float32)

def create_object(shader):
    # Create a new VAO (Vertex Array Object) and bind it
    vertex_array_object = GL.glGenVertexArrays(1)
    GL.glBindVertexArray( vertex_array_object )
    
    # Generate buffers to hold our vertices
    vertex_buffer = GL.glGenBuffers(1)
    GL.glBindBuffer(GL.GL_ARRAY_BUFFER, vertex_buffer)
    
    # Get the position of the 'position' in parameter of our shader and bind it.
    position = GL.glGetAttribLocation(shader, 'position')
    GL.glEnableVertexAttribArray(position)
    
    # Describe the position data layout in the buffer
    GL.glVertexAttribPointer(position, 4, GL.GL_FLOAT, False, 0, ctypes.c_void_p(0))
    
    # Send the data over to the buffer
    GL.glBufferData(GL.GL_ARRAY_BUFFER, 48, vertices, GL.GL_STATIC_DRAW)
    
    # Unbind the VAO first (Important)
    GL.glBindVertexArray( 0 )
    
    # Unbind other stuff
    GL.glDisableVertexAttribArray(position)
    GL.glBindBuffer(GL.GL_ARRAY_BUFFER, 0)
    
    return vertex_array_object
    
def display(shader, vertex_array_object):
    GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
    GL.glUseProgram(shader)
    
    GL.glBindVertexArray( vertex_array_object )
    GL.glDrawArrays(GL.GL_TRIANGLES, 0, 3)
    GL.glBindVertexArray( 0 )
    
    GL.glUseProgram(0)

def main():
    pygame.init()
    screen = pygame.display.set_mode((512, 512), pygame.OPENGL|pygame.DOUBLEBUF)
    GL.glClearColor(0.5, 0.5, 0.5, 1.0)
    GL.glEnable(GL.GL_DEPTH_TEST)

    shader = OpenGL.GL.shaders.compileProgram(
        OpenGL.GL.shaders.compileShader(vertex_shader, GL.GL_VERTEX_SHADER),
        OpenGL.GL.shaders.compileShader(fragment_shader, GL.GL_FRAGMENT_SHADER)
    )
    
    vertex_array_object = create_object(shader)
    
    clock = pygame.time.Clock()
    
    while True:     
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return
            if event.type == pygame.KEYUP and event.key == pygame.K_ESCAPE:
                return
        
        display(shader, vertex_array_object)
        pygame.display.flip()

if __name__ == '__main__':
    try:
        main()
    finally:
        pygame.quit()

## basicWindow from glGA

In [ ]:
from sdl2 import *
import sdl2.ext
import imgui as ImGui
from imgui.integrations.sdl2 import SDL2Renderer


def init():
    if SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) != 0:
        print("SDL could not initialize! SDL Error: ", SDL_GetError())
        exit(1)

    print("Yay! Initialized SDL successfully!")
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE)
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1)
    # SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 16)
    # SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2)

    # CREATE WINDOW
    window_title = 'BasicWindow'
    windowWidth = 1024
    windowHeight = 768
    gWindow = SDL_CreateWindow(window_title.encode(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                               windowWidth, windowHeight, SDL_WINDOW_OPENGL)
    if gWindow is None:
        print("Window could not be created! SDL Error: ", SDL_GetError())
        exit(1)

    print("Yay! Created window successfully!\n\n")
    gContext = SDL_GL_CreateContext(gWindow)
    if gContext is None:
        print("OpenGL context could not be created! SDL Error: ", SDL_GetError())
        exit(1)

    SDL_GL_MakeCurrent(gWindow, gContext)
    if SDL_GL_SetSwapInterval(1) < 0:
        print("Warning: Unable to set VSync! SDL Error: " + SDL_GetError())
        exit(1)

    return gWindow, gContext

def impl_pysdl2_init():
    width, height = 1280, 720
    window_name = "minimal ImGui/SDL2 example"

    if SDL_Init(SDL_INIT_EVERYTHING) < 0:
        print("Error: SDL could not initialize! SDL Error: " + SDL_GetError())
        exit(1)

    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1)
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24)
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8)
    SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1)
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1)
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 16)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE)

    SDL_SetHint(SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK, b"1")
    SDL_SetHint(SDL_HINT_VIDEO_HIGHDPI_DISABLED, b"1")

    window = SDL_CreateWindow(window_name.encode('utf-8'),
                              SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                              width, height,
                              SDL_WINDOW_OPENGL|SDL_WINDOW_RESIZABLE)

    if window is None:
        print("Error: Window could not be created! SDL Error: " + SDL_GetError())
        exit(1)

    gl_context = SDL_GL_CreateContext(window)
    if gl_context is None:
        print("Error: Cannot create OpenGL Context! SDL Error: " + SDL_GetError())
        exit(1)

    SDL_GL_MakeCurrent(window, gl_context)
    if SDL_GL_SetSwapInterval(1) < 0:
        print("Warning: Unable to set VSync! SDL Error: " + SDL_GetError())
        exit(1)

    return window, gl_context

def main():
    simpleInit = False
    if simpleInit:
        gWindow, gContext = init()
    else:
        gWindow, gContext = impl_pysdl2_init()

    ImGui.create_context()
    impl = SDL2Renderer(gWindow)

    running = True
    event = SDL_Event()
    renderer = SDL2Renderer(gWindow)

    running = True
    # MAIN LOOP
    while running:
        events = sdl2.ext.get_events()
        for event in events:
            if event.type == SDL_KEYDOWN:
                if event.key.keysym.sym == SDLK_ESCAPE:
                    running = False
            if event.type == SDL_QUIT:
                running = False
            renderer.process_event(event)
        renderer.process_inputs()
        
        # start new frame context
        ImGui.new_frame()

        # open new window context
        ImGui.begin("Our first window!", True)

        # draw text label inside of current window
        ImGui.text("PyImgui + PySDL2 integration successful!")

        # close current window context
        ImGui.end()

        # pass all drawing commands to the rendering pipeline
        # and close frame context
        ImGui.render()

        SDL_GL_SwapWindow(gWindow)
    # CLOSING
    renderer.shutdown()
    SDL_GL_DeleteContext(gContext)
    SDL_DestroyWindow(gWindow)
    SDL_Quit()


if __name__ == "__main__":
    main()

In [ ]:
import turtle

help(turtle.pencolor)

## Progress Bar tests

In [ ]:
#tqdm example 1
from tqdm import tqdm
from time import sleep

text = ""
for char in tqdm(["a", "b", "c", "d"]):
    sleep(0.25)
    text = text + char

In [ ]:
#tqdm example 2
pbar = tqdm(total=100)
for i in range(10):
    sleep(0.1)
    pbar.update(10)
pbar.close()

In [ ]:
#tqdm example 3
from tqdm import tqdm, trange
from random import random, randint
from time import sleep

with trange(10) as t:
    for i in t:
        # Description will be displayed on the left
        t.set_description('GEN %i' % i)
        # Postfix will be displayed on the right,
        # formatted automatically based on argument's datatype
        t.set_postfix(loss=random(), gen=randint(1,999), str='h',
                      lst=[1, 2])
        sleep(0.1)

with tqdm(total=10, bar_format="{postfix[0]} {postfix[1][value]:>8.2g}",
          postfix=["Batch", dict(value=0)]) as t:
    for i in range(10):
        sleep(0.1)
        t.postfix[1]["value"] = i / 2
        t.update()

In [ ]:
#tqdm example 4 with nice jupyter output
from tqdm.notebook import trange, tqdm
from time import sleep

for i in trange(3, desc='1st loop'):
    for j in tqdm(range(100), desc='2nd loop'):
        sleep(0.01)

In [ ]:
# alive-progress example 1
from alive_progress import alive_bar
items = range(1000)                  # retrieve your set of items
with alive_bar(len(items)) as bar:   # declare your expected total
    for item in items:               # iterate as usual
        # process each item
        bar()                        # call after consuming one item

In [ ]:
# alive-progress example 2
from alive_progress import showtime
#showtime() #hangs up jupyter

In [ ]:
%load_ext version_information

%version_information
%version_information scipy, numpy, Cython, matplotlib, qutip, version_information

In [ ]:
#from OpenGL import *
import OpenGL.GL as gl


In [ ]:
help(OpenGL)

In [ ]:
import OpenGL.GL as myGL

In [ ]:
help (myGL)